# Generated by Django 3.2.12 on 2022-11-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20221104_2246"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(default="", max_length=225),
        ),
    ]
