# Generated by Django 3.2.12 on 2022-11-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
