# Generated by Django 3.2.16 on 2022-11-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_auto_20221110_0916"),
        ("authentication", "0004_auto_20221110_2259"),
    ]

    operations = []
