# Generated by Django 3.2.16 on 2022-11-06 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_auto_20221105_1630"),
        ("authentication", "0004_auto_20221105_1636"),
    ]

    operations = []
