# Generated by Django 3.2.16 on 2022-11-05 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Server', max_length=125)),
                ('provider', models.CharField(blank=True, default='', max_length=125)),
                ('url', models.CharField(max_length=225)),
                ('webhook_url', models.CharField(blank=True, default='', max_length=225)),
                ('api_ping_url', models.CharField(blank=True, default='', max_length=225)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerPingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinged_back', models.BooleanField(default=True)),
                ('url_pinged', models.CharField(max_length=225)),
                ('status_code', models.IntegerField(null=True)),
                ('response_html', models.CharField(max_length=255, null=True)),
                ('time_taken', models.DurationField(default=datetime.timedelta(0))),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
