# Generated by Django 3.2.16 on 2022-11-16 23:51

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=125)),
                ("provider", models.CharField(blank=True, default="", max_length=125)),
                (
                    "url",
                    models.CharField(
                        max_length=225,
                    ),
                ),
                (
                    "webhook_url",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                (
                    "api_ping_url",
                    models.CharField(blank=True, default="", max_length=225),
                ),
                ("active", models.BooleanField(default=True)),
                ("api_percentage_uptime", models.FloatField(default=0)),
                ("api_last_ping_status", models.BooleanField(default=True)),
                ("frontend_percentage_uptime", models.FloatField(default=0)),
                ("frontend_last_ping_status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServerPingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pinged_back", models.BooleanField(default=True)),
                ("url_pinged", models.CharField(max_length=225)),
                ("status_code", models.IntegerField(null=True)),
                ("time_taken", models.DurationField(default=datetime.timedelta(0))),
                ("response_mimetype", models.CharField(max_length=225, null=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="servers.server"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
