# Generated by Django 3.2.16 on 2022-11-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serverpinghistory",
            name="response_html",
        ),
        migrations.AddField(
            model_name="server",
            name="percentage_uptime",
            field=models.FloatField(default=0),
        ),
    ]
