# Generated by Django 3.2.12 on 2022-11-05 13:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverpinghistory",
            name="time_taken",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
