# Generated by Django 3.2.16 on 2022-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=125),
        ),
    ]
