# Generated by Django 3.2.12 on 2022-11-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_alter_serverpinghistory_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="server",
            name="api_ping_url",
            field=models.CharField(blank=True, default="", max_length=225),
        ),
    ]
