# Generated by Django 3.2.16 on 2022-11-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_auto_20221106_0134"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="percentage_uptime",
            new_name="api_percentage_uptime",
        ),
        migrations.AddField(
            model_name="server",
            name="frontend_percentage_uptime",
            field=models.FloatField(default=0),
        ),
    ]
