# Generated by Django 3.2.16 on 2022-12-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_server_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverpinghistory',
            name='mode',
            field=models.CharField(choices=[('api', 'Api'), ('frontend', 'Frontend')], default='api', max_length=225),
        ),
    ]
