# Generated by Django 3.2.16 on 2022-11-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_alter_server_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverpinghistory",
            name="response_html",
            field=models.TextField(null=True),
        ),
    ]
