# Generated by Django 3.2.12 on 2022-11-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_auto_20221104_2122"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="webhook_url",
            field=models.CharField(blank=True, default="", max_length=225),
        ),
    ]
