# Generated by Django 3.2.16 on 2022-11-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0003_auto_20221106_0151"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="api_last_ping_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="server",
            name="api_poisson",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="server",
            name="api_reliability_index",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="server",
            name="frontend_last_ping_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="server",
            name="frontend_poisson",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="server",
            name="frontend_reliability_index",
            field=models.FloatField(default=0),
        ),
    ]
