version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"
    ignore:
      # ignore all patch updates since we are using ~=
      # this does not work for security updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "npm"
    directory: "/urNode-frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"
    ignore:
      # ignore all patch updates since we are using ~=
      # this does not work for security updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "docker"
    directory: "./"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "dependabot-validation"
    ignore:
      # ignore all patch updates since we are using ~=
      # this does not work for security updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    target-branch: "develop"
    ignore:
      # ignore all patch updates since we are using ~=
      # this does not work for security updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
