repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^(migrations/)
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          [
            "--profile",
            "black",
            "--filter-files",
            "--skip",
            "venv",
          ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.16.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.16.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@8.5.0
          - eslint-plugin-import@2.26.0
          - eslint-plugin-jsx-a11y@6.5.1
          - eslint-plugin-react@7.30.0
          - eslint-plugin-react-hooks@4.5.0
        args: ["--fix"]
        files: frontend/src/
