version: '3.8'

services:
   backend:
    container_name: backend_demo_app_eye
    expose:
      - "8000"
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
      - DEMO_INSTANCE=true     
  