FROM python:3.8.5-alpine

RUN apk add --no-cache gcc musl-dev python3-dev


RUN pip install --upgrade pip

COPY ./ /app

WORKDIR /app
RUN pip install -r ./requirements/run-requirements.txt

ENTRYPOINT ["sh","/entrypoint.sh"]