# Generated by Django 3.2.16 on 2022-11-10 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CloudProvider",
        ),
    ]
