version: "3.7"

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8000:8000"
  postgres:
    image: library/postgres:12-alpine
    container_name: eye_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env_file_postgres

volumes:
  postgres_data:
  static:
  
backend:
    build:
      dockerfile: Dockerfile_guicorn

frontend:
    build:
      dockerfile: Dockerfile_react