# Generated by Django 3.2.12 on 2022-10-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0003_alter_shirts_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='size',
            field=models.CharField(choices=[('xs', 'Xs'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'Xl')], max_length=10),
        ),
    ]
