# Generated by Django 3.2.12 on 2022-10-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0004_alter_shirts_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirts',
        ),
    ]
